import React from "react";
import { Box } from "@mui/material";
import Grid from "@mui/material/Grid";
import Paper from "@mui/material/Paper";
import { styled } from "@mui/material/styles";
import HtmlIcon from "@mui/icons-material/Html";
import PictureAsPdfIcon from "@mui/icons-material/PictureAsPdf";
import DownloadIcon from "@mui/icons-material/Download";


const Item = styled(Paper)(({ theme }) => ({
	backgroundColor: "rgba(0, 0, 0, 0)",
	padding: theme.spacing(5),
	textAlign: "center",
	marginTop: "50px",
	elevation: 0,
    boxShadow: "none",
	"& h1": {
		color: "white",
        fontFamily: 'Alata',
        fontSize: "1.6em",
	},
}));



export default function AboutGrid() {
	return (
		<Box sx={{ flexGrow: 1 }}>
			<Grid container spacing={1}>
				<Grid xs>
					<Item>
						<HtmlIcon sx={{ color: "white", fontSize: "100px" }} />
						<div>
							<h1>Copy and paste your link into the field above!</h1>
						</div>
					</Item>
				</Grid>
				<Grid xs>
					<Item>
						<PictureAsPdfIcon sx={{ color: "white", fontSize: "100px" }} />

						<div>
							
								<h1>Wait for the PDF to be generated by the HTML2PDF API! </h1>
							
						</div>
					</Item>
				</Grid>
				<Grid xs>
					<Item>
						<DownloadIcon sx={{ color: "white", fontSize: "100px" }} />
						<div>
							<h1>Download your file. It's that simple!</h1>
						</div>
					</Item>
				</Grid>
			</Grid>
		</Box>
	);
}
